name: Build & Attach ZIP
on:
push:
tags:
- 'v*.*.*'
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Zip extension
run: |
cd extension
zip -r ../page-anonymizer-${GITHUB_REF_NAME}.zip .
- name: Upload artifact
uses: actions/upload-artifact@v4
with:
name: page-anonymizer-${{ github.ref_name }}.zip
path: page-anonymizer-${{ github.ref_name }}.zip
